---
- hosts: all
  become: true

  vars_files:
    - web_vars.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.apache
    - geerlingguy.php

  tasks:
    - name: Remove apache test page
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy my custom test page
      template:
        src: ../templates/index.php.j2
        dest: /var/www/html/index.php
